### ISSUE TITLE
search-subtitles: highlight only shows first part of line not after match

### ISSUE THREAD

**Issue by mrfragger** [zenwarr/mpv-config#14]
```
-- highlight found text with colored text in ass syntax
-- todo: it breaks current item highlighting right now   
```

` return before .. "{\\c&HFF00&}" .. match .. "{\\c&HFFFFFF&}" .. after`

I spent hours trying to figure this out..mainly cuz I don't know lua....anyway I learned a bit about string.sub, string.gsub, string.match.  So `match` is `green` and `after` is `white` to make it match the rest of the text.  

I couldn't figure out where the light blue highlight color is coming from for 

```
local cur_line = {sub}
    for _, line in ipairs(get_lines(data)) do
        line = trim(line)
        if state == "header" then
            if line == "" then
                state = "body"
            end
        elseif state == "body" then
            if line == "" then
                state = "header"
            elseif line:match("^NOTE") or line:match("^STYLE") then
                state = "comment"
```

Anyway I suggest to solve this issue is remove the light blue color and just bold the entire current line if that's possible.

**Comment by zenwarr** [comment]
It comes from `script-modules/scroll-list.lua`, and `scroll_list:format_line` function applies the style. Your proposed solution is good, but I personally prefer to keep selected line colored and plan to fix the script to work correctly, because bold selection leads to text jumps and can be not noticeable enough depending on a font.

But if you prefer to remove the color and use bold for the current line, you can edit `script-modules/scroll-list.lua` and set values for corresponding lines like this:

```lua
list_style = [[{\q2\fs25\c&Hffffff&\b0}]],
```

and 

```lua
selected_style = [[{\b1\c&Hffffff&}]],
```

**Comment by zenwarr** [comment]
I've fixed color highlighting too

**Comment by mrfragger** [comment]
Awesome...much appreciated.  I'm trying out the new one and it seems like it's returning results but it's all blank.  Tried on mkv video and also opus audiobook.
![Screen Shot 2023-09-30 at 3 23 11 PM](https://github.com/zenwarr/mpv-config/assets/80211672/ee2eacae-1f6f-4f72-bd71-38594b8c8811)

**Comment by mrfragger** [comment]
ok I'm an idiot..updated the scroll-list.lua and input-console.lua and works fabulously
![Screen Shot 2023-09-30 at 3 37 19 PM](https://github.com/zenwarr/mpv-config/assets/80211672/8239dbd1-34f1-4a38-b0e5-22f21c7eb1e8)
